name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild -project Redditor.xcodeproj -scheme Redditor -sdk iphonesimulator build
    - name: Run tests
      run: xcodebuild -scheme "Redditor" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11" test-without-building
